name: AdvancedMobArena
version: '${project.version}'
main: su.nightexpress.ama.AMA
author: NightExpress
depend: [ NexEngine ]
softdepend:
  - Vault
  - MythicMobs
  - EliteMobs
  - BossMania
  - mcMMO
  - MMOCore
  - HolographicDisplays
  - DecentHolograms
  - PlaceholderAPI
  - SunLight
  - Essentials
  - CoinsEngine
description: Advanced mob arena with many cool features for your server. Enjoy!
api-version: 1.18