name: AdvancedMobArena
version: '${project.version}'
main: su.nightexpress.ama.AMA
author: NightExpress
depend: [ NexEngine ]
softdepend:
  - Vault
  - MythicMobs
  - EliteMobs
  - BossMania
  - mcMMO
  - HolographicDisplays
  - DecentHolograms
  - Citizens
  - PlaceholderAPI
  - SunLight
  - Essentials
  - GamePoints
  - PlayerPoints
loadbefore: [ Magic ]
description: An advanced mob arena with many cool features for your server. Enjoy!
api-version: 1.17